package com.zhousl.aether.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.ArrowDropDown
import androidx.compose.material.icons.rounded.Check
import androidx.compose.material.icons.rounded.Refresh
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.DropdownMenu
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.Stable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.Saver
import androidx.compose.runtime.saveable.listSaver
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.text.TextRange
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.TextFieldValue
import androidx.compose.ui.unit.dp
import com.zhousl.aether.data.LlmProvider
import com.zhousl.aether.data.LlmProviderConfig
import com.zhousl.aether.data.isProviderSetupValid
import com.zhousl.aether.data.isValidProviderId
import com.zhousl.aether.data.requiresApiKey
import com.zhousl.aether.data.sanitizeProviderId
import com.zhousl.aether.ui.theme.AetherOnSurface
import com.zhousl.aether.ui.theme.AetherOnSurfaceVariant
import com.zhousl.aether.ui.theme.AetherSurfaceHigh
import java.util.UUID

private val ProviderFormPrimary = Color(0xFF5C5C5C)

@Stable
class ProviderFormState internal constructor(
    private val existingConfig: LlmProviderConfig?,
    providerId: String,
    name: String,
    providerStorageValue: String,
    apiKey: String,
    baseUrl: String,
    modelId: String,
    cachedModels: List<String>,
    enabledModelIds: List<String>,
    providerIdManuallyEdited: Boolean = existingConfig != null,
    lastAutoGeneratedProviderId: String = providerId,
) {
    var providerId by mutableStateOf(providerId)
    var name by mutableStateOf(name)
    var providerStorageValue by mutableStateOf(providerStorageValue)
    var apiKey by mutableStateOf(apiKey)
    var baseUrl by mutableStateOf(baseUrl)
    var modelId by mutableStateOf(modelId)
    var cachedModels by mutableStateOf(cachedModels)
    var enabledModelIds by mutableStateOf(enabledModelIds)
    var isFetchingModelsLocally by mutableStateOf(false)
    private var providerIdManuallyEdited by mutableStateOf(providerIdManuallyEdited)
    private var lastAutoGeneratedProviderId by mutableStateOf(lastAutoGeneratedProviderId)

    val selectedProvider: LlmProvider
        get() = LlmProvider.fromStorage(providerStorageValue)

    val allModels: List<String>
        get() = (cachedModels + modelId)
            .map(String::trim)
            .filter(String::isNotEmpty)
            .distinct()

    val effectiveModelId: String
        get() = enabledModelIds.firstOrNull()
            ?: modelId.trim().ifBlank { allModels.firstOrNull().orEmpty() }

    val isCurrentlyEnabled: Boolean
        get() = existingConfig?.isEnabled ?: true

    val isProviderIdManuallyEdited: Boolean
        get() = providerIdManuallyEdited

    val currentAutoGeneratedProviderId: String
        get() = lastAutoGeneratedProviderId

    fun updateName(value: String) {
        name = value
        updateAutoGeneratedProviderId()
    }

    fun setProviderIdFromUser(value: String) {
        providerId = value
        providerIdManuallyEdited = value.isNotBlank() && value != lastAutoGeneratedProviderId
    }

    fun isValid(existingProviderIds: Set<String>): Boolean {
        val trimmedProviderId = providerId.trim()
        val providerIdAvailable = trimmedProviderId !in (existingProviderIds - setOf(existingConfig?.providerId.orEmpty()))
        return providerIdAvailable &&
            isValidProviderId(trimmedProviderId) &&
            isProviderSetupValid(
                provider = selectedProvider,
                apiKey = apiKey,
                baseUrl = baseUrl,
                modelId = effectiveModelId,
            )
    }

    fun applyProviderDefaults(newProvider: LlmProvider) {
        val previousProvider = selectedProvider
        providerStorageValue = newProvider.storageValue
        if (baseUrl.isBlank() || baseUrl.trim() == previousProvider.defaultBaseUrl) {
            baseUrl = newProvider.defaultBaseUrl
        }
        if (modelId.isBlank() || modelId.trim() == previousProvider.defaultModelId) {
            modelId = newProvider.defaultModelId
        }
        if (!providerIdManuallyEdited) {
            updateAutoGeneratedProviderId()
        } else if (providerId.isBlank() || providerId.trim() == previousProvider.storageValue) {
            providerId = newProvider.storageValue
        }
    }

    private fun updateAutoGeneratedProviderId() {
        if (providerIdManuallyEdited) return
        val generatedProviderId = name.sanitizeProviderId().ifBlank { selectedProvider.storageValue }
        providerId = generatedProviderId
        lastAutoGeneratedProviderId = generatedProviderId
    }

    fun setModelEnabled(
        model: String,
        enabled: Boolean,
    ) {
        enabledModelIds = if (enabled) {
            (enabledModelIds + model).map(String::trim).filter(String::isNotEmpty).distinct()
        } else {
            enabledModelIds.filterNot { it == model }
        }
    }

    fun applyFetchedModels(models: List<String>) {
        val normalizedCurrent = allModels.toSet()
        val normalizedModels = models
            .map(String::trim)
            .filter(String::isNotEmpty)
            .distinct()
        cachedModels = normalizedModels
        enabledModelIds = normalizedModels.filter { model ->
            enabledModelIds.contains(model) || !normalizedCurrent.contains(model)
        }
        if (modelId.trim().isBlank() || modelId !in (normalizedModels + modelId)) {
            modelId = normalizedModels.firstOrNull().orEmpty()
        }
    }

    fun buildConfig(): LlmProviderConfig = LlmProviderConfig(
        id = existingConfig?.id ?: UUID.randomUUID().toString(),
        providerId = providerId.trim().sanitizeProviderId(),
        name = name.trim().ifBlank { selectedProvider.displayName },
        providerType = selectedProvider,
        apiKey = apiKey.trim(),
        baseUrl = baseUrl.trim(),
        modelId = effectiveModelId.ifBlank { selectedProvider.defaultModelId },
        cachedModels = allModels,
        enabledModelIds = enabledModelIds
            .map(String::trim)
            .filter { it.isNotEmpty() && allModels.contains(it) }
            .distinct(),
        isEnabled = existingConfig?.isEnabled ?: true,
        createdAtMillis = existingConfig?.createdAtMillis ?: System.currentTimeMillis(),
    )

    companion object {
        fun fromConfig(existingConfig: LlmProviderConfig?): ProviderFormState {
            val initialProvider = existingConfig?.providerType ?: LlmProvider.OpenAiCompatible
            val initialModelId = existingConfig?.modelId ?: initialProvider.defaultModelId
            val initialModels = (existingConfig?.cachedModels.orEmpty() + initialModelId)
                .map(String::trim)
                .filter(String::isNotEmpty)
                .distinct()
            val initialEnabledModels = if (existingConfig != null) {
                existingConfig.enabledModelIds
                    .map(String::trim)
                    .filter { it.isNotEmpty() && initialModels.contains(it) }
                    .distinct()
            } else {
                listOf(initialModelId)
            }
            return ProviderFormState(
                existingConfig = existingConfig,
                providerId = existingConfig?.providerId ?: initialProvider.storageValue,
                name = existingConfig?.name.orEmpty(),
                providerStorageValue = initialProvider.storageValue,
                apiKey = existingConfig?.apiKey.orEmpty(),
                baseUrl = existingConfig?.baseUrl ?: initialProvider.defaultBaseUrl,
                modelId = initialModelId,
                cachedModels = initialModels,
                enabledModelIds = initialEnabledModels,
            )
        }
    }
}

@Composable
fun rememberProviderFormState(
    existingConfig: LlmProviderConfig?,
): ProviderFormState = rememberSaveable(
    existingConfig?.id,
    saver = providerFormStateSaver(existingConfig),
) {
    ProviderFormState.fromConfig(existingConfig)
}

@Composable
fun ProviderConfigurationForm(
    state: ProviderFormState,
    existingProviderIds: Set<String>,
    isFetchingModels: Boolean,
    onFetchModels: (LlmProviderConfig, (List<String>) -> Unit) -> Unit,
    modifier: Modifier = Modifier,
    cardColor: Color = AetherSurfaceHigh,
) {
    val selectedProvider = state.selectedProvider
    val providerIdAlreadyUsed = state.providerId.trim() in (existingProviderIds - setOf(state.buildConfig().providerId))
    val providerIdError = when {
        state.providerId.isBlank() -> "Provider ID is required."
        !isValidProviderId(state.providerId.trim()) -> "Use lowercase letters, numbers, and underscores only."
        providerIdAlreadyUsed -> "This provider ID is already in use."
        else -> ""
    }

    Column(
        modifier = modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(16.dp),
    ) {
        ProviderFormCard(cardColor = cardColor) {
            ProviderFormTextField(
                label = "Provider name",
                value = state.name,
                onValueChange = state::updateName,
            )
            ProviderFormDivider()
            ProviderFormTextField(
                label = "Provider ID",
                value = state.providerId,
                onValueChange = state::setProviderIdFromUser,
            )
        }

        if (providerIdError.isNotBlank()) {
            Text(
                text = providerIdError,
                style = MaterialTheme.typography.bodySmall,
                color = Color(0xFFD25757),
                modifier = Modifier.padding(horizontal = 4.dp),
            )
        }

        ProviderFormCard(cardColor = cardColor) {
            ProviderFormDropdownField(
                label = "Request format",
                selectedValue = selectedProvider.displayName,
                options = LlmProvider.entries,
                onSelected = state::applyProviderDefaults,
            )
        }

        Text(
            text = when (selectedProvider) {
                LlmProvider.OpenAiResponses -> "Use OpenAI-compatible /responses endpoints."
                LlmProvider.OpenAiCompatible -> "Use OpenAI-compatible /chat/completions endpoints."
                LlmProvider.VertexExpress -> "Use Vertex AI Express Mode generateContent."
                LlmProvider.AnthropicMessages -> "Use Anthropic-compatible /messages endpoints."
            },
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
            modifier = Modifier.padding(horizontal = 4.dp),
        )

        ProviderFormCard(cardColor = cardColor) {
            ProviderFormTextField(
                label = "API Key",
                value = state.apiKey,
                onValueChange = { state.apiKey = it },
            )
            ProviderFormDivider()
            ProviderFormTextField(
                label = "Base URL",
                value = state.baseUrl,
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Uri),
                onValueChange = { state.baseUrl = it },
            )
            ProviderFormDivider()
            ProviderFormTextField(
                label = "Manual model ID",
                value = state.modelId,
                onValueChange = { state.modelId = it },
            )
            ProviderFormDivider()
            ProviderModelListField(
                models = state.allModels,
                enabledModelIds = state.enabledModelIds,
                isFetchingModels = state.isFetchingModelsLocally || isFetchingModels,
                onToggleModel = state::setModelEnabled,
                onFetchModels = {
                    state.isFetchingModelsLocally = true
                    onFetchModels(state.buildConfig()) { models ->
                        state.applyFetchedModels(models)
                        state.isFetchingModelsLocally = false
                    }
                },
            )
        }

        Text(
            text = if (selectedProvider.requiresApiKey) {
                "Enabled models appear in the chat model picker. This request format requires an API key."
            } else {
                "Enabled models appear in the chat model picker. Refresh loads models from the provider API."
            },
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
            modifier = Modifier.padding(horizontal = 4.dp),
        )
    }
}

private fun providerFormStateSaver(
    existingConfig: LlmProviderConfig?,
): Saver<ProviderFormState, Any> = listSaver(
    save = { state ->
        listOf(
            state.providerId,
            state.name,
            state.providerStorageValue,
            state.apiKey,
            state.baseUrl,
            state.modelId,
            state.cachedModels,
            state.enabledModelIds,
            state.isProviderIdManuallyEdited,
            state.currentAutoGeneratedProviderId,
        )
    },
    restore = { restored ->
        @Suppress("UNCHECKED_CAST")
        ProviderFormState(
            existingConfig = existingConfig,
            providerId = restored[0] as String,
            name = restored[1] as String,
            providerStorageValue = restored[2] as String,
            apiKey = restored[3] as String,
            baseUrl = restored[4] as String,
            modelId = restored[5] as String,
            cachedModels = restored[6] as List<String>,
            enabledModelIds = restored[7] as List<String>,
            providerIdManuallyEdited = restored.getOrNull(8) as? Boolean ?: (existingConfig != null),
            lastAutoGeneratedProviderId = restored.getOrNull(9) as? String ?: restored[0] as String,
        )
    },
)

@Composable
private fun ProviderFormCard(
    cardColor: Color,
    content: @Composable () -> Unit,
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .background(cardColor, RoundedCornerShape(20.dp)),
    ) {
        content()
    }
}

@Composable
private fun ProviderFormDivider() {
    Spacer(modifier = Modifier.height(8.dp))
}

@Composable
private fun ProviderFormTextField(
    label: String,
    value: String,
    onValueChange: (String) -> Unit,
    modifier: Modifier = Modifier,
    keyboardOptions: KeyboardOptions = KeyboardOptions.Default,
) {
    var fieldValue by rememberSaveable(label, stateSaver = TextFieldValue.Saver) {
        mutableStateOf(TextFieldValue(value, selection = TextRange(value.length)))
    }

    LaunchedEffect(value) {
        if (value != fieldValue.text) {
            fieldValue = TextFieldValue(value, selection = TextRange(value.length))
        }
    }

    Column(
        modifier = modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 14.dp),
    ) {
        Text(
            text = label,
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
        )
        Spacer(modifier = Modifier.height(6.dp))
        BasicTextField(
            value = fieldValue,
            onValueChange = {
                fieldValue = it
                onValueChange(it.text)
            },
            modifier = Modifier.fillMaxWidth(),
            textStyle = MaterialTheme.typography.bodyLarge.copy(color = AetherOnSurface),
            cursorBrush = SolidColor(ProviderFormPrimary),
            keyboardOptions = keyboardOptions,
            decorationBox = { innerTextField ->
                Box {
                    if (fieldValue.text.isEmpty()) {
                        Text(
                            text = label,
                            style = MaterialTheme.typography.bodyLarge,
                            color = AetherOnSurfaceVariant.copy(alpha = 0.5f),
                        )
                    }
                    innerTextField()
                }
            },
        )
    }
}

@Composable
private fun ProviderFormDropdownField(
    label: String,
    selectedValue: String,
    options: List<LlmProvider>,
    onSelected: (LlmProvider) -> Unit,
) {
    var expanded by remember { mutableStateOf(false) }

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { expanded = true }
            .padding(horizontal = 16.dp, vertical = 14.dp),
    ) {
        Text(
            text = label,
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
        )
        Spacer(modifier = Modifier.height(4.dp))
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text(
                text = selectedValue,
                style = MaterialTheme.typography.bodyLarge,
                color = AetherOnSurface,
            )
            Icon(
                imageVector = Icons.Rounded.ArrowDropDown,
                contentDescription = "Choose provider",
                tint = AetherOnSurfaceVariant,
            )
        }
        DropdownMenu(
            expanded = expanded,
            onDismissRequest = { expanded = false },
            modifier = Modifier.background(Color.White),
        ) {
            options.forEach { option ->
                DropdownMenuItem(
                    text = { Text(option.displayName, color = AetherOnSurface) },
                    trailingIcon = if (option.displayName == selectedValue) {
                        { Icon(Icons.Rounded.Check, contentDescription = null, tint = ProviderFormPrimary) }
                    } else {
                        null
                    },
                    onClick = {
                        expanded = false
                        onSelected(option)
                    },
                )
            }
        }
    }
}

@Composable
private fun ProviderModelListField(
    models: List<String>,
    enabledModelIds: List<String>,
    isFetchingModels: Boolean,
    onToggleModel: (String, Boolean) -> Unit,
    onFetchModels: () -> Unit,
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 14.dp),
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.SpaceBetween,
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = "Model list",
                    style = MaterialTheme.typography.bodySmall,
                    color = AetherOnSurfaceVariant,
                )
                Spacer(modifier = Modifier.height(4.dp))
                Text(
                    text = if (models.isEmpty()) {
                        "No models loaded yet."
                    } else {
                        "${enabledModelIds.size}/${models.size} enabled"
                    },
                    style = MaterialTheme.typography.bodyMedium,
                    color = AetherOnSurface,
                )
            }
            if (isFetchingModels) {
                CircularProgressIndicator(
                    modifier = Modifier.size(24.dp),
                    strokeWidth = 2.dp,
                    color = ProviderFormPrimary,
                )
            } else {
                IconButton(onClick = onFetchModels) {
                    Icon(
                        imageVector = Icons.Rounded.Refresh,
                        contentDescription = "Fetch models",
                        tint = ProviderFormPrimary,
                    )
                }
            }
        }

        if (models.isNotEmpty()) {
            Spacer(modifier = Modifier.height(10.dp))
            Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                models.forEach { model ->
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clickable { onToggleModel(model, !enabledModelIds.contains(model)) }
                            .padding(vertical = 2.dp),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Checkbox(
                            checked = enabledModelIds.contains(model),
                            onCheckedChange = { checked -> onToggleModel(model, checked) },
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = model,
                            style = MaterialTheme.typography.bodyMedium,
                            color = AetherOnSurface,
                        )
                    }
                }
            }
        }
    }
}
