package com.zhousl.aether.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.Add
import androidx.compose.material.icons.rounded.ArrowDropDown
import androidx.compose.material.icons.rounded.Check
import androidx.compose.material.icons.rounded.Delete
import androidx.compose.material.icons.rounded.Refresh
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.DropdownMenu
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.Stable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.Saver
import androidx.compose.runtime.saveable.listSaver
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.TextRange
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.TextFieldValue
import androidx.compose.ui.unit.dp
import com.zhousl.aether.R
import com.zhousl.aether.data.LlmProvider
import com.zhousl.aether.data.LlmProviderConfig
import com.zhousl.aether.data.LlmCustomHeader
import com.zhousl.aether.data.isProviderSetupValid
import com.zhousl.aether.data.isValidProviderId
import com.zhousl.aether.data.requiresApiKey
import com.zhousl.aether.data.sanitizeProviderId
import com.zhousl.aether.ui.theme.AetherOnSurface
import com.zhousl.aether.ui.theme.AetherOnSurfaceVariant
import com.zhousl.aether.ui.theme.AetherSurfaceHigh
import java.util.UUID

private val ProviderFormPrimary = Color(0xFF5C5C5C)

@Stable
class ProviderFormState internal constructor(
    private val existingConfig: LlmProviderConfig?,
    providerId: String,
    name: String,
    providerStorageValue: String,
    apiKey: String,
    baseUrl: String,
    modelId: String,
    customHeaders: List<LlmCustomHeader>,
    cachedModels: List<String>,
    enabledModelIds: List<String>,
    basicFunctionCallingCompatibilityMode: Boolean,
    providerIdManuallyEdited: Boolean = existingConfig != null,
    lastAutoGeneratedProviderId: String = providerId,
) {
    var providerId by mutableStateOf(providerId)
    var name by mutableStateOf(name)
    var providerStorageValue by mutableStateOf(providerStorageValue)
    var apiKey by mutableStateOf(apiKey)
    var baseUrl by mutableStateOf(baseUrl)
    var modelId by mutableStateOf(modelId)
    var customHeaders by mutableStateOf(customHeaders)
    var cachedModels by mutableStateOf(cachedModels)
    var enabledModelIds by mutableStateOf(enabledModelIds)
    var basicFunctionCallingCompatibilityMode by mutableStateOf(basicFunctionCallingCompatibilityMode)
    var isFetchingModelsLocally by mutableStateOf(false)
    private var providerIdManuallyEdited by mutableStateOf(providerIdManuallyEdited)
    private var lastAutoGeneratedProviderId by mutableStateOf(lastAutoGeneratedProviderId)

    val selectedProvider: LlmProvider
        get() = LlmProvider.fromStorage(providerStorageValue)

    val allModels: List<String>
        get() = normalizeModelIds(cachedModels + manualModelIds)

    private val manualModelIds: List<String>
        get() = parseManualModelIds(modelId)

    val effectiveModelId: String
        get() = enabledModelIds.firstOrNull()
            ?: manualModelIds.firstOrNull()
            ?: allModels.firstOrNull().orEmpty()

    val isCurrentlyEnabled: Boolean
        get() = existingConfig?.isEnabled ?: true

    val isProviderIdManuallyEdited: Boolean
        get() = providerIdManuallyEdited

    val currentAutoGeneratedProviderId: String
        get() = lastAutoGeneratedProviderId

    fun updateName(value: String) {
        name = value
        updateAutoGeneratedProviderId()
    }

    fun setProviderIdFromUser(value: String) {
        providerId = value
        providerIdManuallyEdited = value.isNotBlank() && value != lastAutoGeneratedProviderId
    }

    fun isValid(existingProviderIds: Set<String>): Boolean {
        val trimmedProviderId = providerId.trim()
        val providerIdAvailable = trimmedProviderId !in (existingProviderIds - setOf(existingConfig?.providerId.orEmpty()))
        return providerIdAvailable &&
            isValidProviderId(trimmedProviderId) &&
            isProviderSetupValid(
                provider = selectedProvider,
                apiKey = apiKey,
                baseUrl = baseUrl,
                modelId = effectiveModelId,
            )
    }

    fun applyProviderDefaults(newProvider: LlmProvider) {
        val previousProvider = selectedProvider
        providerStorageValue = newProvider.storageValue
        if (baseUrl.isBlank() || baseUrl.trim() == previousProvider.defaultBaseUrl) {
            baseUrl = newProvider.defaultBaseUrl
        }
        if (modelId.isBlank() || modelId.trim() == previousProvider.defaultModelId) {
            modelId = newProvider.defaultModelId
        }
        if (!providerIdManuallyEdited) {
            updateAutoGeneratedProviderId()
        } else if (providerId.isBlank() || providerId.trim() == previousProvider.storageValue) {
            providerId = newProvider.storageValue
        }
    }

    private fun updateAutoGeneratedProviderId() {
        if (providerIdManuallyEdited) return
        val generatedProviderId = name.sanitizeProviderId().ifBlank { selectedProvider.storageValue }
        providerId = generatedProviderId
        lastAutoGeneratedProviderId = generatedProviderId
    }

    fun setModelEnabled(
        model: String,
        enabled: Boolean,
    ) {
        val normalizedModel = model.trim()
        enabledModelIds = if (enabled) {
            normalizeModelIds(enabledModelIds + normalizedModel)
        } else {
            enabledModelIds.filterNot { it == normalizedModel }
        }
    }

    fun applyFetchedModels(models: List<String>) {
        val normalizedCurrent = allModels.toSet()
        val normalizedModels = models
            .map(String::trim)
            .filter(String::isNotEmpty)
            .distinct()
        cachedModels = normalizedModels
        val availableModels = normalizeModelIds(normalizedModels + manualModelIds)
        val newlyFetchedModels = normalizedModels.filter { model -> !normalizedCurrent.contains(model) }
        enabledModelIds = normalizeModelIds(enabledModelIds + newlyFetchedModels)
            .filter(availableModels::contains)
    }

    fun addCustomHeader() {
        customHeaders = customHeaders + LlmCustomHeader("", "")
    }

    fun updateCustomHeader(
        index: Int,
        name: String = customHeaders.getOrNull(index)?.name.orEmpty(),
        value: String = customHeaders.getOrNull(index)?.value.orEmpty(),
    ) {
        customHeaders = customHeaders.mapIndexed { headerIndex, header ->
            if (headerIndex == index) {
                header.copy(name = name, value = value)
            } else {
                header
            }
        }
    }

    fun removeCustomHeader(index: Int) {
        customHeaders = customHeaders.filterIndexed { headerIndex, _ -> headerIndex != index }
    }

    fun buildConfig(): LlmProviderConfig = LlmProviderConfig(
        id = existingConfig?.id ?: UUID.randomUUID().toString(),
        providerId = providerId.trim().sanitizeProviderId(),
        name = name.trim().ifBlank { selectedProvider.displayName },
        providerType = selectedProvider,
        apiKey = apiKey.trim(),
        baseUrl = baseUrl.trim(),
        modelId = effectiveModelId.ifBlank { selectedProvider.defaultModelId },
        manualModelIds = manualModelIds,
        customHeaders = customHeaders
            .map { header -> LlmCustomHeader(header.name.trim(), header.value) }
            .filter { header -> header.name.isNotBlank() },
        cachedModels = normalizeModelIds(cachedModels),
        enabledModelIds = enabledModelIds
            .map(String::trim)
            .filter { it.isNotEmpty() && allModels.contains(it) }
            .distinct(),
        isEnabled = existingConfig?.isEnabled ?: true,
        basicFunctionCallingCompatibilityMode = basicFunctionCallingCompatibilityMode,
        createdAtMillis = existingConfig?.createdAtMillis ?: System.currentTimeMillis(),
    )

    companion object {
        fun fromConfig(existingConfig: LlmProviderConfig?): ProviderFormState {
            val initialProvider = existingConfig?.providerType ?: LlmProvider.OpenAiCompatible
            val initialModelId = existingConfig?.modelId ?: initialProvider.defaultModelId
            val initialManualModels = existingConfig?.manualModelIds
                ?.takeIf { it.isNotEmpty() }
                ?: listOf(initialModelId)
            val initialModels = (existingConfig?.cachedModels.orEmpty() + initialManualModels)
                .map(String::trim)
                .filter(String::isNotEmpty)
                .distinct()
            val initialEnabledModels = if (existingConfig != null) {
                existingConfig.enabledModelIds
                    .map(String::trim)
                    .filter { it.isNotEmpty() && initialModels.contains(it) }
                    .distinct()
            } else {
                listOf(initialModelId)
            }
            return ProviderFormState(
                existingConfig = existingConfig,
                providerId = existingConfig?.providerId ?: initialProvider.storageValue,
                name = existingConfig?.name.orEmpty(),
                providerStorageValue = initialProvider.storageValue,
                apiKey = existingConfig?.apiKey.orEmpty(),
                baseUrl = existingConfig?.baseUrl ?: initialProvider.defaultBaseUrl,
                modelId = initialManualModels.joinToString("\n"),
                customHeaders = existingConfig?.customHeaders.orEmpty(),
                cachedModels = existingConfig?.cachedModels.orEmpty(),
                enabledModelIds = initialEnabledModels,
                basicFunctionCallingCompatibilityMode =
                    existingConfig?.basicFunctionCallingCompatibilityMode ?: false,
            )
        }
    }
}

@Composable
fun rememberProviderFormState(
    existingConfig: LlmProviderConfig?,
): ProviderFormState = rememberSaveable(
    existingConfig?.id,
    saver = providerFormStateSaver(existingConfig),
) {
    ProviderFormState.fromConfig(existingConfig)
}

@Composable
fun ProviderConfigurationForm(
    state: ProviderFormState,
    existingProviderIds: Set<String>,
    isFetchingModels: Boolean,
    onFetchModels: (LlmProviderConfig, (List<String>) -> Unit) -> Unit,
    onModelEnabledChange: (LlmProviderConfig) -> Unit = {},
    modifier: Modifier = Modifier,
    cardColor: Color = AetherSurfaceHigh,
) {
    val selectedProvider = state.selectedProvider
    val providerIdAlreadyUsed = state.providerId.trim() in (existingProviderIds - setOf(state.buildConfig().providerId))
    val providerIdError = when {
        state.providerId.isBlank() -> stringResource(R.string.provider_form_provider_id_required)
        !isValidProviderId(state.providerId.trim()) -> stringResource(R.string.provider_form_provider_id_invalid)
        providerIdAlreadyUsed -> stringResource(R.string.provider_form_provider_id_in_use)
        else -> ""
    }

    Column(
        modifier = modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(16.dp),
    ) {
        ProviderFormCard(cardColor = cardColor) {
            ProviderFormTextField(
                label = stringResource(R.string.provider_form_provider_name),
                value = state.name,
                onValueChange = state::updateName,
            )
            ProviderFormDivider()
            ProviderFormTextField(
                label = stringResource(R.string.provider_form_provider_id),
                value = state.providerId,
                onValueChange = state::setProviderIdFromUser,
            )
        }

        if (providerIdError.isNotBlank()) {
            Text(
                text = providerIdError,
                style = MaterialTheme.typography.bodySmall,
                color = Color(0xFFD25757),
                modifier = Modifier.padding(horizontal = 4.dp),
            )
        }

        ProviderFormCard(cardColor = cardColor) {
            ProviderFormDropdownField(
                label = stringResource(R.string.provider_form_request_format),
                selectedValue = selectedProvider.displayName,
                options = LlmProvider.entries,
                onSelected = state::applyProviderDefaults,
            )
        }

        Text(
            text = when (selectedProvider) {
                LlmProvider.OpenAiResponses -> stringResource(R.string.provider_form_request_format_openai_responses)
                LlmProvider.OpenAiCompatible -> stringResource(R.string.provider_form_request_format_openai_chat_completions)
                LlmProvider.VertexExpress -> stringResource(R.string.provider_form_request_format_vertex_express)
                LlmProvider.AnthropicMessages -> stringResource(R.string.provider_form_request_format_anthropic_messages)
            },
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
            modifier = Modifier.padding(horizontal = 4.dp),
        )

        ProviderFormCard(cardColor = cardColor) {
            ProviderCompatibilityModeField(
                enabled = state.basicFunctionCallingCompatibilityMode,
                onEnabledChange = { state.basicFunctionCallingCompatibilityMode = it },
            )
        }

        Text(
            text = stringResource(R.string.provider_form_compatibility_mode_description),
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
            modifier = Modifier.padding(horizontal = 4.dp),
        )

        ProviderFormCard(cardColor = cardColor) {
            ProviderFormTextField(
                label = stringResource(R.string.provider_form_api_key),
                value = state.apiKey,
                onValueChange = { state.apiKey = it },
            )
            ProviderFormDivider()
            ProviderFormTextField(
                label = stringResource(R.string.provider_form_base_url),
                value = state.baseUrl,
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Uri),
                onValueChange = { state.baseUrl = it },
            )
            ProviderFormDivider()
            ProviderFormTextField(
                label = stringResource(R.string.provider_form_manual_model_ids),
                value = state.modelId,
                onValueChange = { state.modelId = it },
            )
            ProviderFormDivider()
            ProviderModelListField(
                models = state.allModels,
                enabledModelIds = state.enabledModelIds,
                isFetchingModels = state.isFetchingModelsLocally || isFetchingModels,
                onToggleModel = { model, enabled ->
                    state.setModelEnabled(model, enabled)
                    onModelEnabledChange(state.buildConfig())
                },
                onFetchModels = {
                    state.isFetchingModelsLocally = true
                    onFetchModels(state.buildConfig()) { models ->
                        state.applyFetchedModels(models)
                        state.isFetchingModelsLocally = false
                    }
                },
            )
            ProviderFormDivider()
            ProviderCustomHeadersField(
                headers = state.customHeaders,
                onAddHeader = state::addCustomHeader,
                onUpdateHeader = state::updateCustomHeader,
                onRemoveHeader = state::removeCustomHeader,
            )
        }

        Text(
            text = if (selectedProvider.requiresApiKey(state.baseUrl)) {
                stringResource(R.string.provider_form_model_picker_requires_api_key)
            } else {
                stringResource(R.string.provider_form_model_picker_refresh_hint)
            },
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
            modifier = Modifier.padding(horizontal = 4.dp),
        )
    }
}

private fun providerFormStateSaver(
    existingConfig: LlmProviderConfig?,
): Saver<ProviderFormState, Any> = listSaver(
    save = { state ->
        listOf(
            state.providerId,
            state.name,
            state.providerStorageValue,
            state.apiKey,
            state.baseUrl,
            state.modelId,
            state.customHeaders.map { listOf(it.name, it.value) },
            state.cachedModels,
            state.enabledModelIds,
            state.basicFunctionCallingCompatibilityMode,
            state.isProviderIdManuallyEdited,
            state.currentAutoGeneratedProviderId,
        )
    },
    restore = { restored ->
        @Suppress("UNCHECKED_CAST")
        val customHeadersIndex = 6
        val hasCustomHeaders = restored.size >= 12
        val modelIndexOffset = if (hasCustomHeaders) 1 else 0
        val restoredCustomHeaders = if (hasCustomHeaders) {
            (restored[customHeadersIndex] as List<*>)
                .mapNotNull { item ->
                    val values = item as? List<*> ?: return@mapNotNull null
                    LlmCustomHeader(
                        name = values.getOrNull(0) as? String ?: "",
                        value = values.getOrNull(1) as? String ?: "",
                    )
                }
        } else {
            existingConfig?.customHeaders.orEmpty()
        }
        ProviderFormState(
            existingConfig = existingConfig,
            providerId = restored[0] as String,
            name = restored[1] as String,
            providerStorageValue = restored[2] as String,
            apiKey = restored[3] as String,
            baseUrl = restored[4] as String,
            modelId = restored[5] as String,
            customHeaders = restoredCustomHeaders,
            cachedModels = restored[6 + modelIndexOffset] as List<String>,
            enabledModelIds = restored[7 + modelIndexOffset] as List<String>,
            basicFunctionCallingCompatibilityMode = restored.getOrNull(8 + modelIndexOffset) as? Boolean
                ?: existingConfig?.basicFunctionCallingCompatibilityMode
                ?: false,
            providerIdManuallyEdited = restored.getOrNull(9 + modelIndexOffset) as? Boolean ?: (existingConfig != null),
            lastAutoGeneratedProviderId = restored.getOrNull(10 + modelIndexOffset) as? String ?: restored[0] as String,
        )
    },
)

internal fun parseManualModelIds(value: String): List<String> =
    normalizeModelIds(value.split('\n', ',', ';').map(String::trim))

private fun normalizeModelIds(values: List<String>): List<String> =
    values
        .map(String::trim)
        .filter(String::isNotEmpty)
        .distinct()

@Composable
private fun ProviderCompatibilityModeField(
    enabled: Boolean,
    onEnabledChange: (Boolean) -> Unit,
) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { onEnabledChange(!enabled) }
            .padding(horizontal = 16.dp, vertical = 14.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween,
    ) {
        Column(modifier = Modifier.weight(1f)) {
            Text(
                text = stringResource(R.string.provider_form_basic_tool_compatibility),
                style = MaterialTheme.typography.bodyLarge,
                color = AetherOnSurface,
            )
            Spacer(modifier = Modifier.height(4.dp))
            Text(
                text = if (enabled) stringResource(R.string.common_on) else stringResource(R.string.common_off),
                style = MaterialTheme.typography.bodySmall,
                color = AetherOnSurfaceVariant,
            )
        }
        Switch(
            checked = enabled,
            onCheckedChange = onEnabledChange,
        )
    }
}

@Composable
private fun ProviderFormCard(
    cardColor: Color,
    content: @Composable () -> Unit,
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .background(cardColor, RoundedCornerShape(20.dp)),
    ) {
        content()
    }
}

@Composable
private fun ProviderFormDivider() {
    Spacer(modifier = Modifier.height(8.dp))
}

@Composable
private fun ProviderFormTextField(
    label: String,
    value: String,
    onValueChange: (String) -> Unit,
    modifier: Modifier = Modifier,
    keyboardOptions: KeyboardOptions = KeyboardOptions.Default,
) {
    var fieldValue by rememberSaveable(label, stateSaver = TextFieldValue.Saver) {
        mutableStateOf(TextFieldValue(value, selection = TextRange(value.length)))
    }

    LaunchedEffect(value) {
        if (value != fieldValue.text) {
            fieldValue = TextFieldValue(value, selection = TextRange(value.length))
        }
    }

    Column(
        modifier = modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 14.dp),
    ) {
        Text(
            text = label,
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
        )
        Spacer(modifier = Modifier.height(6.dp))
        BasicTextField(
            value = fieldValue,
            onValueChange = {
                fieldValue = it
                onValueChange(it.text)
            },
            modifier = Modifier.fillMaxWidth(),
            textStyle = MaterialTheme.typography.bodyLarge.copy(color = AetherOnSurface),
            cursorBrush = SolidColor(ProviderFormPrimary),
            keyboardOptions = keyboardOptions,
            decorationBox = { innerTextField ->
                Box {
                    if (fieldValue.text.isEmpty()) {
                        Text(
                            text = label,
                            style = MaterialTheme.typography.bodyLarge,
                            color = AetherOnSurfaceVariant.copy(alpha = 0.5f),
                        )
                    }
                    innerTextField()
                }
            },
        )
    }
}

@Composable
private fun ProviderFormDropdownField(
    label: String,
    selectedValue: String,
    options: List<LlmProvider>,
    onSelected: (LlmProvider) -> Unit,
) {
    var expanded by remember { mutableStateOf(false) }

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { expanded = true }
            .padding(horizontal = 16.dp, vertical = 14.dp),
    ) {
        Text(
            text = label,
            style = MaterialTheme.typography.bodySmall,
            color = AetherOnSurfaceVariant,
        )
        Spacer(modifier = Modifier.height(4.dp))
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text(
                text = selectedValue,
                style = MaterialTheme.typography.bodyLarge,
                color = AetherOnSurface,
            )
            Icon(
                imageVector = Icons.Rounded.ArrowDropDown,
                contentDescription = stringResource(R.string.provider_form_choose_provider),
                tint = AetherOnSurfaceVariant,
            )
        }
        DropdownMenu(
            expanded = expanded,
            onDismissRequest = { expanded = false },
            modifier = Modifier.background(Color.White),
        ) {
            options.forEach { option ->
                DropdownMenuItem(
                    text = { Text(option.displayName, color = AetherOnSurface) },
                    trailingIcon = if (option.displayName == selectedValue) {
                        { Icon(Icons.Rounded.Check, contentDescription = null, tint = ProviderFormPrimary) }
                    } else {
                        null
                    },
                    onClick = {
                        expanded = false
                        onSelected(option)
                    },
                )
            }
        }
    }
}

@Composable
private fun ProviderModelListField(
    models: List<String>,
    enabledModelIds: List<String>,
    isFetchingModels: Boolean,
    onToggleModel: (String, Boolean) -> Unit,
    onFetchModels: () -> Unit,
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 14.dp),
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.SpaceBetween,
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = stringResource(R.string.provider_form_model_list),
                    style = MaterialTheme.typography.bodySmall,
                    color = AetherOnSurfaceVariant,
                )
                Spacer(modifier = Modifier.height(4.dp))
                Text(
                    text = if (models.isEmpty()) {
                        stringResource(R.string.provider_form_no_models_loaded)
                    } else {
                        stringResource(R.string.provider_form_models_enabled_count, enabledModelIds.size, models.size)
                    },
                    style = MaterialTheme.typography.bodyMedium,
                    color = AetherOnSurface,
                )
            }
            if (isFetchingModels) {
                CircularProgressIndicator(
                    modifier = Modifier.size(24.dp),
                    strokeWidth = 2.dp,
                    color = ProviderFormPrimary,
                )
            } else {
                IconButton(onClick = onFetchModels) {
                    Icon(
                        imageVector = Icons.Rounded.Refresh,
                        contentDescription = stringResource(R.string.provider_form_fetch_models),
                        tint = ProviderFormPrimary,
                    )
                }
            }
        }

        if (models.isNotEmpty()) {
            Spacer(modifier = Modifier.height(10.dp))
            Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                models.forEach { model ->
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clickable { onToggleModel(model, !enabledModelIds.contains(model)) }
                            .padding(vertical = 2.dp),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Checkbox(
                            checked = enabledModelIds.contains(model),
                            onCheckedChange = { checked -> onToggleModel(model, checked) },
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = model,
                            style = MaterialTheme.typography.bodyMedium,
                            color = AetherOnSurface,
                        )
                    }
                }
            }
        }
    }
}

@Composable
private fun ProviderCustomHeadersField(
    headers: List<LlmCustomHeader>,
    onAddHeader: () -> Unit,
    onUpdateHeader: (Int, String, String) -> Unit,
    onRemoveHeader: (Int) -> Unit,
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 14.dp),
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.SpaceBetween,
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = stringResource(R.string.provider_form_custom_request_headers),
                    style = MaterialTheme.typography.bodySmall,
                    color = AetherOnSurfaceVariant,
                )
                Spacer(modifier = Modifier.height(4.dp))
                Text(
                    text = if (headers.isEmpty()) stringResource(R.string.common_optional) else stringResource(R.string.provider_form_headers_configured_count, headers.size),
                    style = MaterialTheme.typography.bodyMedium,
                    color = AetherOnSurface,
                )
            }
            IconButton(onClick = onAddHeader) {
                Icon(
                    imageVector = Icons.Rounded.Add,
                    contentDescription = stringResource(R.string.provider_form_add_header),
                    tint = ProviderFormPrimary,
                )
            }
        }

        if (headers.isNotEmpty()) {
            Spacer(modifier = Modifier.height(10.dp))
            Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                headers.forEachIndexed { index, header ->
                    ProviderCustomHeaderRow(
                        header = header,
                        onNameChange = { name -> onUpdateHeader(index, name, header.value) },
                        onValueChange = { value -> onUpdateHeader(index, header.name, value) },
                        onRemove = { onRemoveHeader(index) },
                    )
                }
            }
        }
    }
}

@Composable
private fun ProviderCustomHeaderRow(
    header: LlmCustomHeader,
    onNameChange: (String) -> Unit,
    onValueChange: (String) -> Unit,
    onRemove: () -> Unit,
) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(8.dp),
    ) {
        ProviderFormTextField(
            label = stringResource(R.string.provider_form_header_name),
            value = header.name,
            onValueChange = onNameChange,
            modifier = Modifier.weight(0.42f),
        )
        ProviderFormTextField(
            label = stringResource(R.string.provider_form_header_value),
            value = header.value,
            onValueChange = onValueChange,
            modifier = Modifier.weight(0.58f),
        )
        IconButton(onClick = onRemove) {
            Icon(
                imageVector = Icons.Rounded.Delete,
                contentDescription = stringResource(R.string.provider_form_remove_header),
                tint = AetherOnSurfaceVariant,
            )
        }
    }
}
